#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! -f constant/polyMesh/points -o ! -f constant/polyMesh/points.gz ];then
    (cd ../share
	./Allrun.pre $*
	)
fi
./Allrun.solve $*
./Allrun.post $*
