#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
if [ ${PWD##*/} = "share" ];then
    rm -rf 0 > /dev/null 2>&1
    rm -rf constant/polyMesh > /dev/null 2>&1
else
    cleanDynamicCode
    rm -f {plot,validation}/*.{eps,pdf} > /dev/null 2>&1
    rm -rf logs > /dev/null 2>&1
    rm -rf postProcessing > /dev/null 2>&1
fi


# ----------------------------------------------------------------- end-of-file
