#!/bin/sh

if [ -f Allcases ];then
    Allcases=`tr '\n' ' ' < Allcases`
else
    Allcases=`ls -d */ | tr -d '/' | tr '\n' ' '`
fi

for dir in $Allcases
do
    if [ -d "$dir" -a "$dir" != "share" -a "$dir" != "validation" ];then
	(cd $dir
	    ./Allrun $*
	    )
    fi
done

# ----------------------------------------------------------------- end-of-file
